In [1]:
import lux

In [2]:
#Importamos y guardamos el dataframe

import pandas as pd

RUTA_DATAFRAME = '../data/processed/df_final.csv'

df = pd.read_csv(RUTA_DATAFRAME, sep=',')

In [3]:
df

/home/tr4shhh/venv/lib/python3.11/site-packages/IPython/core/formatters.py:922: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues

/home/tr4shhh/venv/lib/python3.11/site-packages/lux/core/frame.py:632: UserWarning:Traceback (most recent call last):
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/core/frame.py", line 594, in _ipython_display_
    self.maintain_recs()
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/core/frame.py", line 436, in maintain_recs
    custom_action_collection = custom_actions(rec_df)
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/action/custom.py", line 76, in custom_actions
    recommendation = lux.config.actions[action_name].action(ldf)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/action/correlation.py", line 50, in correlation
    vlist = VisList(intent, ldf)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/vis/VisList.py", line 43, in __init__
    self.refresh_source(self._source)
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/vis/VisList.py", line 336, in refresh_source
    lux.config.executor.execute(self._collection, ldf, approx=approx)
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/executor/PandasExecutor.py", line 147, in execute
    PandasExecutor.execute_2D_binning(vis)
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/executor/PandasExecutor.py", line 413, in execute_2D_binning
    vis._vis_data["xBin"] = pd.cut(vis._vis_data[x_attr], bins=lux.config.heatmap_bin_size)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/reshape/tile.py", line 258, in cut
    rng = (nanops.nanmin(x), nanops.nanmax(x))
           ^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/nanops.py", line 147, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/nanops.py", line 404, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/nanops.py", line 1089, in reduction
    values, mask = _get_values(
                   ^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/nanops.py", line 315, in _get_values
    values = values.copy()
             ^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/generic.py", line 6687, in copy
    return self._constructor_from_mgr(data, axes=data.axes).__finalize__(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/series.py", line 589, in _constructor_from_mgr
    return self._constructor(ser, copy=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/lux/core/series.py", line 69, in __init__
    super(LuxSeries, self).__init__(*args, **kw)
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/series.py", line 475, in __init__
    data, index = self._init_dict(data, index, dtype)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/series.py", line 549, in _init_dict
    if data:
  File "/home/tr4shhh/venv/lib/python3.11/site-packages/pandas/core/generic.py", line 1519, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

,0,1,2,3,4,5,6,7,8,9,...,0,1,2,3,4,5,6,7,8,9
0,16.0,1.0,60.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,9.0,4.0,1.0,2.0,0.0,5.0,2.0,1.0,3.0,0.0
1,16.0,2.0,87.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,NaN,3.0,1.0,2.0,0.0,1.0,9.0,3.0,3.0,0.0
2,16.0,1.0,38.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,9.0,4.0,1.0,4.0,0.0,4.0,3.0,3.0,2.0,0.0
3,16.0,2.0,43.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,8.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,3.0,0.0
4,16.0,1.0,41.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,...,NaN,4.0,1.0,5.0,0.0,4.0,3.0,1.0,3.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22067,19.0,1.0,23.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,NaN,1.0,1.0,2.0,0.0,5.0,3.0,1.0,3.0,0.0
22068,19.0,2.0,31.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,NaN,4.0,1.0,2.0,0.0,2.0,2.0,1.0,3.0,0.0
22069,19.0,2.0,79.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,NaN,4.0,1.0,1.0,0.0,9.0,3.0,1.0,3.0,0.0
22070,19.0,2.0,60.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,NaN,4.0,1.0,2.0,0.0,5.0,3.0,1.0,3.0,0.0
22071,19.0,1.0,72.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,...,NaN,4.0,1.0,1.0,0.0,3.0,3.0,1.0,3.0,0.0